apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: 365657944743.dkr.ecr.us-east-1.amazonaws.com/ultimateci-cd:6
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-secret
